version: '3.9'

services:

  transactions:
    build: ./transactionManagement
    env_file:
      - ./transactionManagement/.env
    ports:
      - "3002:8000"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - transaction_net
    depends_on:
      db_transaction:
        condition: service_healthy

  db_transaction:
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=transactions
    networks:
      - transaction_net
    ports:
      - 5435:5432
    volumes:
      - transactions_postgres_temp:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5

networks:
  transaction_net:
    driver: bridge

volumes:
  transactions_postgres_temp:
